# El archivo entero es un Workflow:
# - Se liga al repo donde se encuentra
# - Se va definiendo a partir de los "Jobs" que incluye
# - Define el Trigger original que podra ejecutar el Workflow, por ejemplo un evento como un "Push"
# ----------------------------------------------------------------------------------------------------------------------
name: First GA # Nombre del Workflow
on: workflow_dispatch # Trigger, en este caso se ejecutara solo manualmente.
# ----------------------------------------------------------------------------------------------------------------------
# A partir de "Jobs" se define uno o mas Jobs a ejecutar, siendo cada Job un proceso completo en algun sentido.
# Cada Job por si mismo ira definiendo:
# - El Runner: Donde se ejecutara el Job, una VM+OS generalmente gestionada y proveida por Github.
#              Es posible usar runners personalizados, desde un proveedor Cloud por ejemplo.
# - Los Steps: Las tareas puntuales requeridas para completar el Job.
# 
# Por default, los Jobs se ejecutan en paralelo, pero pueden ser sequenciales si se desea.
# Tambien es posible condicionar la ejecucion de un Job.
# ----------------------------------------------------------------------------------------------------------------------
jobs: # Inician las descripciones de Jobs
# ----------------------------------------------------------------------------------------------------------------------
  first-job: # Nombre de este Job
    runs-on: ubuntu-latest # El Runner del Job
# ----------------------------------------------------------------------------------------------------------------------
# Los Steps ejecutan cmds de Shell o un "Action". Las Actions pueden ser personalizadas o usar una del Market que ofrece 
# Github(muchas son gratuitas, pero pueden generar costos tambien).
# Cada Step sera ejecutado linealmente uno a uno. Tambien puede ser condicionada la ejecucion del Step.
# Los Steps se definen con un nombre y su accion
# ----------------------------------------------------------------------------------------------------------------------
    steps:
      - name: Print Hello # Nombre del Step
        run: echo "Waaaazaaaaa!!!" # Shell ejecutado por el Step
      - name: Print Bye
        run: | # Tambien es posible el uso de Steps multilinea
          echo "Waaaazaaaaaa!!!"
          ls
          echo "See you bro!"
